services:
  - type: web
    name: ats-resume-matcher
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python build.py
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
